### ISSUE TITLE
Tips on how to expose internal Swift classes/methods to generated ObjC header

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [ios-bazel-users/ios-bazel-users#38]
Hello There,

I am working on building a framework target via Bazel and I am running into issues with my internal swift classes not appearing in the generated ObjC `-Swift.h` header. Is there any sort of flag I can pass to allow these classes and methods to appear in the generated header?

Thank you

**Comment by keith** [comment]
Sorry I meant to reply here. Did you figure this out?

**Comment by tinder-maxwellelliott** [comment]
Hey there @Keith,

So I thin the answer here is that what I am trying to do is actually impossible. I am attempting to migrate a _massive_ iOS application target to use a framework instead, yet the rules behind both of those targets work are fundamentally different. 

The issue is that the rules that allow this `ios_application` target to compile are invalid in a framework target, i.e. no bridging headers, you need to have proper ACLs on declarations. There appears to be no easy way to fix this, and my resolution is to fix all the ACL violations
