### ISSUE TITLE
Facing issues loading Localized strings in `ios_application` rule

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [ios-bazel-users/ios-bazel-users#40]
Hello there,

I am facing issues with loading Localized strings in an `ios_application` rule as follows:

```
ios_application(
    name = "SomeApp",
    srcs = SOURCES,
    bundle_id = "com.app.someapp",
    minimum_os_version = "11.0",
    strings = glob(["Localization/**/*.strings"]) + glob(["Localization/**/*.stringdict"]),
    resources = glob(
            ["Resources/**/*"],
            ["Resources/**/*.appiconset/**"],
            exclude_directories = 0),
)
```

The target can build fine, but when I run tests on this app the Localized strings are not being loaded. Where am I going wrong? `strings` looks like it should be the right option https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application

**Comment by thii** [comment]
Do you have any BUILD files in the Localization directory that makes it a package and stops glob from going deeper?

**Comment by tinder-maxwellelliott** [comment]
Sadly not, `Localization` has no BUILD files in it. I am wondering if I am loading my strings from the Bundle incorrectly. How can I test to see if the Strings are properly being loaded into the Bundle?

**Comment by keith** [comment]
I think you probably want `data` / `resources` not `strings`?

**Comment by tinder-maxwellelliott** [comment]
What is even more perplexing, the `lproj` files are being found correctly, it just not loading the translations from them:

```
@@@@@@@@ Language Code: ja
@@@@@@@@ Bundle Path: /Users/Max/Library/Developer/CoreSimulator/Devices/166B569F-9B1F-4628-B5B0-533B38AC9DEE/data/Containers/Bundle/Application/1DD96B2C-1881-424C-9661-02DBB23284DA/SomeApp.app/ja.lproj
```

@Keith I will try resources instead

**Comment by thii** [comment]
Ah so it does get bundled in the app correctly, probably a problem with the code that loads it?

I think all those attributes work the same now. I think `ios_application`'s `resources` and `strings` are kind of deprecated—you can add your resources to any `{objc,swift}_library`'s `data`/`deps` and they would be bucketized, processed, and bundled properly.

**Comment by tinder-maxwellelliott** [comment]
I am moving these strings into the `data` attribute. The more I look at this, the more I think there is an issue on my end somewhere. I will update here after I look into this more locally

**Comment by tinder-maxwellelliott** [comment]
Update: So I have everything working in my `ios_application` rule (I mispelled `stringsdict` as `stringdict` 🤦🏻 ), but I am now running into a new issue. How can I collect `Localized.strings` files from my modules and use them in my `iOS_application` target? Placing them naively via `filegroups` gives me this error:

```
Error in fail: Multiple files would be placed at "Payload/SomeApp.app/Unlocalized.strings" in the bundle, which is not allowed. check input file:
Projects/Modules/AModule/Localization/Unlocalized.strings
```

**Comment by keith** [comment]
If they're named differently they shouldn't conflict, but how do you do this in Xcode land now? We use resource bundles (for other reasons but it also works for this), but I guess theoretically you'd hope they would be merged or something instead?

**Comment by tinder-maxwellelliott** [comment]
> If they're named differently they shouldn't conflict, but how do you do this in Xcode land now?

What would a valid naming strategy be? Would each need to be named something like `MyModule_en-US_Localized.strings` for each file? I am not totally sure how this is handled now, it must be handled via CocoaPods 

> but I guess theoretically you'd hope they would be merged or something instead?

I do not want merging, ideally I have separate bundles for the main app and the module and I can pick localizations from either by choosing the correct bundle.

**Comment by keith** [comment]
I imagine from the bazel perspective any naming not conflicting would be fine, but then from your code you'd have to make sure to load them from the right files.

Definitely doing resource bundles works fine, you can use the [`apple_resource_bundle`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-resources.md#apple_resource_bundle) rule for that

**Comment by tinder-maxwellelliott** [comment]
`apple_resource_bundle` looks like a great option, going to look into that now

**Comment by tinder-maxwellelliott** [comment]
@Keith How do you consume these `apple_resource_bundle`'s in Swift? I am including them in my targets `data` attribute but  the keys are still not loading. How do you loading them in Swift from the Bundle Bazel creates?

**Comment by keith** [comment]
We have some wrapper like this:

```swift
public struct I18N {
    private let bundle: Bundle
    private let tableName: String

    public init(bundle: Bundle, tableName: String) {
        self.bundle = bundle
        self.tableName = tableName
    }

    public func string(forKey key: String) -> String {
        return NSLocalizedString(key, tableName: self.tableName, bundle: self.bundle, comment: "")
    }
}
```

which we create with the resource bundle as the NSBundle (we generate the code that does that, but that's the idea)

**Comment by tinder-maxwellelliott** [comment]
How do you handle Pluralization with `stringdicts`?

**Comment by keith** [comment]
We don't right now but I'm pretty confident the same approach would work with a slightly different API?

**Comment by tinder-maxwellelliott** [comment]
Closing this for now, yet again I think this issue is on my side. Localizations are being loaded into the simulator when I am running the tests.

**Comment by tinder-maxwellelliott** [comment]
> If they're named differently they shouldn't conflict, but how do you do this in Xcode land now? We use resource bundles (for other reasons but it also works for this), but I guess theoretically you'd hope they would be merged or something instead?

Can I get a simple example of how you use `apple_resource_bundle` and how you consume it in your library targets?

**Comment by thii** [comment]
There're some examples in the rules_apple repo. Here's one of them: https://github.com/bazelbuild/rules_apple/blob/8562971108c11931618a220731c335e9fab9fb49/examples/ios/PrenotCalculator/BUILD#L26-L59

Basically everything in transitive deps' `data` will be propagated when you build your application target.

**Comment by tinder-maxwellelliott** [comment]
So basically you should use `apple_resource_bundle` for all resources and just let Bazel propagate them through?

Looks like that is what is going on here: https://github.com/bazelbuild/rules_apple/blob/572aee29236aa6aa850484d5706b79aa2a098219/test/starlark_tests/resources/BUILD#L441

**Comment by thii** [comment]
I'm not sure about the recommendation but it's what we're doing. It can save you from forgetting to add/remove the apple_resource_bundle targets when the library targets that actually use them are added/removed.

**Comment by tinder-maxwellelliott** [comment]
I couldn't end up getting `apple_resource_bundle` to work as expected. In the end I just wrote Genrules to perform renames of all `*.strings` files for each module and packaging them via `data`, seems to be working fine!

Thanks y'all for the help!
