### ISSUE TITLE
[General Bazel] Tips on consuming private release binaries from Github in Bazel

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [ios-bazel-users/ios-bazel-users#41]
Hello Y'All,

This is not exactly just an iOS question but I was wondering how others are consuming private repository release binaries in Bazel? I would image some users are consuming internal binaries in their Bazel builds instead of rebuilding everything from source. The issue I see is the management of authentication to the private release URLs.

Any help is appreciated!

**Comment by keith** [comment]
we're using public ones, and potentially artifactory in the future. i think there's a token env var for bazelisk you could use if you hosted it on your own github releases on a private repo
